appConfig:
  title: "Mani's Homelab"
  theme: dark
  layout: auto

sections:
  - name: Core Services
    icon: "mdi-server"
    items:
      - title: Uptime Kuma
        url: "http://192.168.8.10:3001"
      - title: Paperless
        url: "http://192.168.8.10:8000"
      - title: Prometheus
        url: "http://192.168.8.10:9090"
      - title: Grafana
        url: "http://192.168.8.10:3002"
      - title: Proxmox-1
        url: "https://192.168.8.11:8006"
      - title: Proxmox-2
        url: "https://192.168.8.12:8006"
      - title: Router
        url: "http://192.168.8.1"
      - title: Glances
        url: "http://192.168.8.10:61208"
