# Starter

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs: [{ targets: ['localhost:9090'] }]

  # To add exporters as deployed:
  # - job_name: 'node_exporter_pi'
  #   static_configs: [{ targets: ['192.168.8.10:9100'] }]

  # - job_name: 'pve_exporter'
  #   static_configs: [{ targets: ['192.168.8.11:9221', '192.168.8.12:9221'] }]
