global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.8.10:9090']

  - job_name: 'pi-node'
    static_configs:
      - targets: ['192.168.8.10:9100']

  - job_name: 'proxmox-nodes'
    static_configs:
      - targets:
          - '192.168.8.11:9100'
          - '192.168.8.12:9100'

#(Saved for later)
#  - job_name: 'proxmox-pve'
#    static_configs:
#      - targets: ['192.168.8.10:9221']

  - job_name: "pi-cadvisor"
    static_configs:
      - targets: ['192.168.8.10:8080']
